logging:
  level:
    com.atguigu.gulimall: debug

gulimall:
  thread:
    core-size: 50
    max-size: 200
    time: 10
    queue-size: 10000


spring:
  session:
    store-type: redis
  main:
    allow-bean-definition-overriding: true