server:
  port: 7000

spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.123:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/**/*.xml