spring:
  cloud:
    gateway:
      routes:
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

        - id: product-route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: coupon-route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**,/hello
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third-part-route
          uri: lb://gulimall-third-part
          predicates:
            - Path=/api/thirdpart/**
          filters:
            - RewritePath=/api/thirdpart(?<segment>.*), /$\{segment}

        - id: member-route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: ware-route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: admin-route
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /gulimall-admin/$\{segment}


        - id: gulimall-host-route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall-search-route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimall-auth-route
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com

        - id: gulimall-cart-route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimall-order-route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimall-member-route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com

        - id: gulimall-seckill-route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com
